name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # 설치할 JDK 배포판 (여기서는 Eclipse Temurin)
          java-version: '17'

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env

      - name: Build with Gradle
        run: ./gradlew build
        # 빌드 과정에서 필요한 추가적인 환경 설정이나 명령어가 있다면 여기에 추가

  deploy:
    runs-on: ubuntu-latest
    needs: build # 빌드 단계가 성공적으로 완료된 후에만 배포 단계가 실행됩니다

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application
        run: ssh -o StrictHostKeyChecking=no chanseo@capstone-backend.comit-server.com "cd /home/chanseo && ./deploy.sh"
        # 서버에서 deploy.sh 스크립트를 실행해 배포